"""One-shot: create an 'Egon — Daily Status' page under the KMS root using
the same internal integration token the push path uses, then print its id.
Output written to logs/_notion_setup.out so a pythonw run leaves no console.
Bruno 2026-05-29."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

OUT = ROOT / "logs" / "_notion_setup.out"


def _write(msg: str) -> None:
    with OUT.open("a", encoding="utf-8") as f:
        f.write(msg + "\n")


def main() -> int:
    OUT.write_text("", encoding="utf-8")
    try:
        import httpx
        from lib.adapters.notion import _token, _headers, KMS_ROOT_ID
    except Exception as e:
        _write(f"IMPORT_FAIL {type(e).__name__}: {e}")
        return 1

    tok = _token()
    if not tok:
        _write("NO_TOKEN")
        return 1

    # First, check if a page titled 'Egon — Daily Status' already exists so we
    # don't create duplicates on re-run.
    try:
        with httpx.Client(timeout=10) as c:
            r = c.post(
                "https://api.notion.com/v1/search",
                headers=_headers(tok),
                json={"query": "Egon — Daily Status",
                      "filter": {"property": "object", "value": "page"},
                      "page_size": 5},
            )
            r.raise_for_status()
            for res in r.json().get("results", []):
                # Title is in properties.title.title[].plain_text for pages
                props = res.get("properties", {})
                for _k, v in props.items():
                    if v.get("type") == "title":
                        txt = "".join(t.get("plain_text", "")
                                      for t in v.get("title", []))
                        if "Egon" in txt and "Daily Status" in txt:
                            _write(f"EXISTS {res['id']}")
                            return 0
    except Exception as e:
        _write(f"SEARCH_WARN {type(e).__name__}: {e}")
        # continue to create

    # Create the page as a child of the KMS root.
    try:
        with httpx.Client(timeout=15) as c:
            r = c.post(
                "https://api.notion.com/v1/pages",
                headers=_headers(tok),
                json={
                    "parent": {"page_id": KMS_ROOT_ID},
                    "properties": {
                        "title": [{
                            "type": "text",
                            "text": {"content": "Egon — Daily Status"},
                        }],
                    },
                    "children": [{
                        "object": "block",
                        "type": "paragraph",
                        "paragraph": {"rich_text": [{
                            "type": "text",
                            "text": {"content": (
                                "Auto-generated by Egon's daily 6 AM pass. "
                                "Each day appends a collapsible 'Egon — YYYY-MM-DD' "
                                "toggle summarising every adapter's status.")},
                        }]},
                    }],
                },
            )
            r.raise_for_status()
            pid = r.json().get("id")
            _write(f"CREATED {pid}")
            return 0
    except Exception as e:
        body = ""
        try:
            body = r.text[:400]
        except Exception:
            pass
        _write(f"CREATE_FAIL {type(e).__name__}: {e} :: {body}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
